### ISSUE TITLE
Performance regression?

### ISSUE THREAD

**Issue by malb** [joostkremers/parsebib#34]
Since the upgrade to the new parsebib version, I can no longer use https://github.com/tmalsburg/helm-bibtex/ and friends. Here's a minimal failing example:

```elisp
(require 'helm-bibtex)
(setq bibtex-completion-bibliography '("PATH/abbrev3.bib" "PATH/crypto_crossref.bib"))
(bibtex-completion-candidates)
```

The two files are:
- [abbrev3](https://cryptobib.di.ens.fr/cryptobib/static/files/abbrev3.bib)
- [crypto_crossref.bib](https://cryptobib.di.ens.fr/cryptobib/static/files/crypto_crossref.bib)

The second is arguably a large file but FWIW it's the standard file everybody in my field uses.

I don't get an error message, it just runs "forever": I killed it after 10 minutes, previously it ran in less than a minute.

**Comment by malb** [comment]
I've reported the issue here https://github.com/tmalsburg/helm-bibtex/issues/456 too because it's not clear to me where the issue lies. Feel free to close this issue if you understand it's not parsebib's "fault".

**Comment by joostkremers** [comment]
It's a performance regression in parsebib, but a strange one... I'm using `signal` to signal errors if they are found, and each call to `signal` contains a call to `format` to create a nice error message detailing exactly what's wrong. As it turns out, it's this `format` that slows down parsing, even though no error is ever signalled! If I remove all the calls to `format` and use just a plain string in the error messages, performance is back to what you describe. (I tested with `crypto_crossref.bib`.)

I'll push a commit to the repo that removes all the `format` calls, so you can get back to doing your work. And I'll raise this on the Emacs mailing list, because there is something weird here.

**Comment by malb** [comment]
That was quick, *thank you*!

**Comment by joostkremers** [comment]
Pushed. Please test. :slightly_smiling_face:

**Comment by malb** [comment]
Yup, it works! Thank you.

**Comment by joostkremers** [comment]
I pushed another commit that brings back more detailed error messages, but now in a way that doesn't affect performance so much. There is still a slight performance impact compared to the previous version with generic error messages (0.7 seconds slower on my machine for `crypto_crossref.bib`) but I think it's acceptable.

The cause of the problem wasn't `format` itself, BTW. Rather, I'm using the functions `line-number-at-pos` and `current-column` to provide an exact location where the parser encounters an error, and one of these (presumably `line-number-at-pos`) is very slow. For a single error message, that's not an issue, but the parser uses errors to trigger backtracking, so it's constantly generating (and capturing) them, so `line-number-at-pos` got called all the time.

The new version includes the value of point in its error data and only calls `line-number-at-pos` if it finds an error that it cannot backtrack from (and so needs to be reported to the user).

**Comment by malb** [comment]
I pulled 20241219.14 from melpa and I agree: performance is fine :)
