### ISSUE TITLE
Believe I have found an off-by-one error in parsebib--match-paren-forward

### ISSUE THREAD

**Issue by rpgoldman** [joostkremers/parsebib#8]
Here's the current definition:
```
(defun parsebib--match-paren-forward ()
  "Move forward to the closing paren matching the opening paren at point.
This function handles parentheses () and braces {}.  Return t if a
matching parenthesis was found.  Note that this function puts
point right before the closing delimiter (unlike e.g.,
`forward-sexp', which puts it right after.)"
  (cond
   ((eq (char-after) ?\{)
    (parsebib--match-brace-forward))
   ((eq (char-after) ?\()
    ;; This is really a hack. We want to allow unbalanced parentheses in
    ;; field values (BibTeX does), so we cannot use forward-sexp
    ;; here. For the same reason, looking for the matching paren by hand
    ;; is pretty complicated. However, balanced parentheses can only be
    ;; used to enclose entire entries (or @STRINGs or @PREAMBLEs) so we
    ;; can be pretty sure we'll find it right before the next @ at the
    ;; start of a line, or right before the end of the file.
    (let ((beg (point)))
      (re-search-forward parsebib--entry-start nil 0)
      (skip-chars-backward "@ \n\t\f")
      (if (eq (char-after) ?\))
          ;; if we've found a closing paren, return t
          t
        ;; otherwise put the cursor back and signal an error
        (goto-char beg)
        (signal 'scan-error (list "Unbalanced parentheses" beg (point-max))))))))
```

This fails to successfully  parse this entry in one of my bib files:
```
@ARTICLE(Stix:LivingRoom,
	AUTHOR = {Gary Stix},
	TITLE = "Domesticating Cyberspace",
	JOURNAL = SciAm,
	YEAR = {1993},
	VOLUME = {269},
	NUMBER = {2},
	PAGES = {100--110},
	MONTH = aug
)

@ARTICLE(Bal:DistPLs,
...
```
What happens when I step through this is that we take the branch for matching parens, then we jump forward to the second `@` (for `Bal:DistPLs`).  The next step is to skip-chars-backward, which puts the cursor right *after* the closing paren that we are looking for.  But the code assumes that the cursor will be right *before* that closing paren -- it checks `(char-after)` when, AFAICT, it should check `(char-before)`.

**Comment by joostkremers** [comment]
Oops... It used to be the case that the delimiter matching functions I use put point right after the closing delimiter, but I changed that when I started using `forward-sexp` to do delimiter matching. I guess I forgot to also change `parsebib--match-paren-forward`, and since it's used very little (Ebib itself uses `{}` to delimit entries), it's never been noticed before.

Thanks for pointing this out, I'll push a fix in a sec.

**Comment by rpgoldman** [comment]
I don't believe you can fix it in this way.  Here's the problem: bib files are allowed to contain arbitrary text between their entries.  For example, you can comment out an entire entry simply by deleting the `@` prefix from the keyword.

But the way you are balancing expressions here assumes that bib files contain *only* correctly-delimited entries, because you assume that the first thing after a closing delimiter will be an `@` character.  I believe that assumption is invalid for many well-formed bib files.

So this should probably become another issue -- parsebib should ignore arbitrary text between entries.

**Comment by rpgoldman** [comment]
To amplify, I believe that this means parsebib cannot simply jump to the end of an entry before parsing the entry.  Instead (because the language of entries is context-free and not regular), parsebib must parse the entry _in order to_ find its closing delimiter.  This is unfortunate, because I suspect it requires extensive rework.

Alternatively, parsebib could reject bib files with random text between entries.  That would not be ideal, but acceptable _but_ in that case it would be critical to detect such text and issue a warning so that the poor user can modify their bib file.

**Comment by rpgoldman** [comment]
I was just poking around in bibtex-mode, and I wonder if you couldn't grab the code from `bibtex-end-of-entry` for some of the things you have been using `parsebib--match-paren-forward` for.  I don't think it would work for everything, because you use your matchers for fields _inside_ an entry, too.  But fields inside an entry are, I believe, easier.  For example, in a string delimited by double quotes, any double quote characters must be escaped.  I can't say for sure, but I believe problems with parsing primarily arise when you are trying to match an entire entry, because in order to match *that*, you have to match all the fields inside.

So if you could swipe `bibtex-end-of-entry` to find entries, then you could keep your existing functions for matching field delimiters, I think.

**Comment by joostkremers** [comment]
You're right, this isn't the best way to solve the issue, though I'm admittedly a bit reluctant to implement a solution using `bibtex-end-of-entry`, because, from the quick look I had, it does indeed parse the entire entry to make sure where it ends. That being the case, I'd rather do the parsing myself. :smile: Which shouldn't be too difficult, I think. `parsebib-read-entry` already assumes that if `parsebib--find-bibtex-field` returns `nil`, the entry has ended.

Alternatively, I could use `bibtex.el` for parsing, but that would also require a substantial rewrite, making `parsebib.el` essentially a library wrapper around `bibtex.el`. (`bibtex.el` doesn't lend itself well to being used as a library, or at least that was my impression when I looked at the code.)

For now, though, I implemented the fix with `bibtex-end-of-entry`, just so the bug doesn't persist. I'll leave the `bibtex.el`-less fix for later.

> So this should probably become another issue -- parsebib should ignore arbitrary text between entries.

While that's essentially true, I should point out that (at the moment) `parsebib.el` cannot retrieve such text snippets from the .bib file. As a result, if you're using Ebib, they will be lost.

**Comment by rpgoldman** [comment]
I agree that bibtex's formatting rules are .... odd.  Allowing random garbage in the files seems almost calculated to make parsing difficult.  But I guess that they didn't ever foresee there being _another_ bibtex parser!

For what it's worth, I have been looking for some way to better curate my bib files, and keep track of the pdfs that correspond to them.  I have tried Zotero (with better bibtex) also, and it likewise has troubles parsing bib files into a database.

Since ebib is a bib _database_, and the random text snippets are just comments -- and not comments attached to any particular entry -- I think it's fine that they are not imported to ebib.

Now that I'm able to get my bib files _into_ ebib, it's time for me to figure out what to do with them there! 😉

**Comment by joostkremers** [comment]
I've started implementing the cross-file `crossref` lookup, though no guarantees when it will be finished. I don't have much time for programming ATM :confused:) I intend to implement it in such a way that cross-references are automatically looked up in all open files, so that you can simply list all your `.bib` files in `ebib-preload-bib-files`.

BTW, Ebib does preserve explicit `@comment` entries, although it saves all of them at the top of the file. Plus there's no way to edit comments within Ebib.

**Comment by rpgoldman** [comment]
This is quite a difficult question, actually -- it's hard to know what ebib should do with cross-references and string definitions.  If you don't expand them, then one can't accurately, for example, search for papers in a conference.  But if you *do* expand them, how do you know to un-expand them when you save the bib database?  Zotero, which does some things similar to ebib, now can import string definitions, but explodes them into its database, so that they are lost.

**Comment by joostkremers** [comment]
Ebib doesn't (and won't) change anything about the database unless you do it explicitly. The only question is how an entry is displayed to the user. If an entry has a `crossref` field, the fields that it inherits from the cross-referenced entry are displayed as well, but in a different color (see, e.g., http://joostkremers.github.io/ebib/images/Search-view.png ), and they're not saved. String definitions are not expanded, but even if I should add that as an option, I wouldn't save them in their expanded form. That would defeat the purpose of string definitions.

The main limitation for your use case is that crossrefs aren't looked up across databases so the effect you see in the screen shot won't actually work in your case. I intend to remedy that, though.

>  If you don't expand them, then one can't accurately, for example, search for papers in a conference.

What exactly is your use case here? I tend to use a filter (on the `crossref` field) to find all the papers in a collection, but perhaps is not what you mean?
